# valores parametrizáveis para garantia-digital

garantiaDigital:
  name: garantia-digital
  namespace: garantia-digital
  domain_name: garantia-service.devops-master.shop
  replicaCount: 1
  image:
    repository: sevenleo/garantia-digital
    tag: mvp
    pullPolicy: IfNotPresent
  service:
    port: 7000
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-staging"
    tls:
      enabled: true
      secretName: garantia-digital-tls

