apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.garantiaDigital.name }}
  namespace: {{ .Values.garantiaDigital.namespace }}
  labels:
    app: {{ .Values.garantiaDigital.name }}
spec:
  replicas: {{ .Values.garantiaDigital.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.garantiaDigital.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.garantiaDigital.name }}
    spec:
      containers:
        - name: {{ .Values.garantiaDigital.name }}
          image: {{ .Values.garantiaDigital.image.repository }}:{{ .Values.garantiaDigital.image.tag }}
          imagePullPolicy: {{ .Values.garantiaDigital.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.garantiaDigital.service.port }}
