apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.garantiaDigital.name }}
  namespace: {{ .Values.garantiaDigital.namespace }}
spec:
  selector:
    app: {{ .Values.garantiaDigital.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.garantiaDigital.service.port }}
      targetPort: {{ .Values.garantiaDigital.service.port }}
