name: Deploy AWS Lambda via Terraform

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::114284751948:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Instalar dependências de sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype6-dev liblcms2-dev

      - name: Instalar dependências Python
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Gerar ZIP do Lambda
        run: |
          mkdir temp_package
          cp src/create-garantia.py temp_package/
          cp src/template-garantia.txt temp_package/
          cp src/logo-backgroud.png temp_package/
          mkdir temp_package/python
          pip install -r src/requirements.txt --target temp_package/python
          cd temp_package
          zip -r ../lambda_function_payload.zip .
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init e Apply
        working-directory: infra
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="lambda_version=${GITHUB_REF_NAME}" \
            -var="email_smtp=${{ secrets.EMAIL_SMTP }}" \
            -var="pass_smtp=${{ secrets.PASS_SMTP }}"
